{% set name = "libertem-asi-tpx3" %}
{% set version = "0.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/libertem_asi_tpx3-{{ version }}.tar.gz
  sha256: 1417135fb4a4b62b9b1e5cc52fbaf327f2634dfcb6788473b40c6c985d330f7d

build:
  skip: True  # [py<37]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python  
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - rust
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=0.13,<0.14
    - pip
    - rust
    - numpy >=1.6.1,<1.24.0
  run:
    - python
    - {{ pin_compatible('numpy', max_pin='x.x') }}

test:
  imports:
    - libertem_asi_tpx3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LiberTEM/LiberTEM-rs/
  summary: LiberTEM support for ASI TPX3 detectors
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  description: |
    A Rust+Python library for receiving sparse array
    streams from Amsterdam Scientific Instruments
    CheeTah TPX3 detectors.

extra:
  recipe-maintainers:
    - sk1p
    - uellue
    - matbryan52
